backgrounds:
  bg001:
    name: 白蛇九十九神社
    file: large_bg001a.png
    variants: 
      bg001a:
        name: 白天
        file: large_bg001a.png
      bg001c:
        name: 夜晚
        file: large_bg001c.png
  bg002:
    name: 白蛇九十九神社附近
    file: large_bg002a.png
    variants:
      bg002a:
        name: 白天
        file: large_bg002a.png
      bg002c:
        name: 夜晚
        file: large_bg002c.png
  bg003:
    name: 白巳津川站
    file: large_bg003a.png
    variants:
      bg003a:
        name: 白天
        file: large_bg003a.png
      bg003b:
        name: 黄昏
        file: large_bg003b.png
      bg003c:
        name: 夜晚
        file: large_bg003c.png
  bg004:
    name: 白巳津川站近郊
    file: large_bg004a.png
    variants:
      bg004a:
        name: 白天
        file: large_bg004a.png
      bg004b:
        name: 黄昏
        file: large_bg004b.png
      bg004c:
        name: 夜晚
        file: large_bg004c.png
  bg014:
    name: 白巳津川公园
    file: large_bg014a.png
    variants:
      bg014a:
        name: 白天
        file: large_bg014a.png
      bg014b:
        name: 黄昏
        file: large_bg014b.png
      bg014c:
        name: 夜晚
        file: large_bg014c.png
  bg005:
    name: 白泉学园校门
    file: large_bg005a.png
  bg006:
    name: 白泉学园走廊
    file: large_bg006a.png
    variants:
      bg006a:
        name: 白天
        file: large_bg006a.png
      bg006b:
        name: 黄昏
        file: large_bg006b.png
      bg006e:
        name: 火焰
        file: large_bg006e.png
  bg007:
    name: 白泉学园教室
    file: large_bg007a.png
    variants:
      bg007a:
        name: 白天
        file: large_bg007a.png
      bg007b:
        name: 黄昏
        file: large_bg007b.png
  bg015:
    name: 白泉学园中庭
    file: large_bg015a.png
  bg008:
    name: 新海翔的家·公寓入口
    file: large_bg008a.png
    variants:
      bg008a:
        name: 白天
        file: large_bg008a.png
      bg008b:
        name: 黄昏
        file: large_bg008b.png
      bg008c:
        name: 夜晚
        file: large_bg008c.png
  bg009:
    name: 新海翔的家·翔的房间
    file: large_bg009a.png
    variants:
      bg009a:
        name: 白天
        file: large_bg009a.png
      bg009b:
        name: 黄昏
        file: large_bg009b.png
      bg009c:
        name: 夜晚
        file: large_bg009c.png
  bg010:
    name: 新海翔的家·厨房
    file: large_bg010a.png
    variants:
      bg010a:
        name: 白天
        file: large_bg010a.png
      bg010b:
        name: 黄昏
        file: large_bg010b.png
      bg010c:
        name: 夜晚
        file: large_bg010c.png
  bg011:
    name: Nine Ball 咖啡店外
    file: large_bg011a.png
    variants:
      bg011a:
        name: 白天
        file: large_bg011a.png
      bg011b:
        name: 黄昏
        file: large_bg011b.png
      bg011c:
        name: 夜晚
        file: large_bg011c.png
  bg012:
    name: Nine Ball 咖啡店内
    file: large_bg012a.png
    variants:
      bg012a:
        name: 白天
        file: large_bg012a.png
      bg012b:
        name: 黄昏
        file: large_bg012b.png
      bg012c:
        name: 夜晚
        file: large_bg012c.png
  bg016:
    name: 家庭餐厅
    file: large_bg016a.png
  bg018:
    name: 购物中心
    file: large_bg018a.png
  bg013:
    name: ROUND2
    file: large_bg013a.png
  bg017:
    name: 神秘大楼
    file: large_bg017a.png
  bg100:
    name: 天空
    file: large_bg100a.png
    variants:
      bg100a:
        name: 白天
        file: large_bg100a.png
      bg100b:
        name: 黄昏
        file: large_bg100b.png
      bg100c:
        name: 夜晚
        file: large_bg100c.png